name: 'Upload a Build Artifact As-Is using node20'
description: 'Uploads a build artifact with its name as-is, that you can download later'
author: 'janishuser'
inputs: 
  path:
    description: 'A file, directory or wildcard pattern that describes what to upload'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
